### PR TITLE
Support shadowDOM parents

### PR DESCRIPTION
**Pull request by MarkChrisLevy**
Allow scrolling into view element, whose parent is in shadow DOM. This is done by testing if either target element or any of it parents has [assignedSlot](https://developer.mozilla.org/en-US/docs/Web/API/Slotable/assignedSlot) - if yes, then get parentElement of assignedSlot.

### CODE REVIEW

**Comment by KoryNunn** [comment]
I'm not sure about this solution, Can you please add a test so I can see the use-case for this? I'm happy to support shadow-dom scenarios but want to be sure it's done right.

**Comment by MarkChrisLevy** [comment]
@KoryNunn Ok, I figured out how make it simpler - instead of predefined parents settings option, I check for assignedSlot - when not empty it means, that element has a parent in shadow DOM. The question is whether to make it work by default or add settings option (checkShadow=true|false).

**Comment by KoryNunn** [comment]
This solution looks much nicer, can you please add a test so that I can merge?

**Comment by MarkChrisLevy** [comment]
@KoryNunn Ok, test added

**Comment by KoryNunn** [comment]
I updated the test to check that the element got scrolled into view and currently it does not.

**Comment by MarkChrisLevy** [comment]
thanks!

**Comment by KoryNunn** [comment]
Hi @MarkChrisLevy I had time to look at this locally, and everything seems to work as expected when I revert the changes to scrollIntoView.js back to master, while leaving the shadow DOM test in. What is the scenario you were seeing where the current version of scroll-into-view didn't work as expected?

**Pull request merged**
