### PR TITLE
Offset

### PR DESCRIPTION
**Pull request by KoryNunn**

### CODE REVIEW

**Comment by KoryNunn** [comment]
@ericvrp I'm pretty sure this is what you're after. Just took your changes but used a pixel offset rather than a scalar.

**Comment by ericvrp** [comment]
That was more or less exactly what I had before I thought you would want the offsets normalized :-) . I will test if this works for me and let you know..

**Comment by ericvrp** [comment]
working!

**Comment by KoryNunn** [comment]
Awesome thanks.

**Pull request merged**
