### PR TITLE
Optional improvements

### PR DESCRIPTION
**Pull request by linuxenko**
There is very sad bug with `touchstart` listeners, i think, it would be cool to have an option that helps disable these listeneres for those who do not use them.

### CODE REVIEW

**Comment by linuxenko** [comment]
Oh, it seems like `npm test` created `browser.build` file..

**Comment by KoryNunn** [comment]
What's the bug you are running into? This event should only fire if you are on a touch device.

I do like the idea of making it non-cancelable, as I can see some use cases for it. I'll have a closer look when I'm at a PC, can't release from my phone :)

**Comment by linuxenko** [comment]
It does not remove listeners. I see about thousands of `touchstart` event listeners navigating over the application.

**Comment by KoryNunn** [comment]
I've fixed the leak here: https://github.com/KoryNunn/scroll-into-view/pull/17

If you still have a use case for disabling the handler that is not related to this issue, let me know.

**Comment by linuxenko** [comment]
yes, maybe you are right. but, i think `touchstart` events should be optional, because there is devices that does not work with any kind of `touch` events (for an instance SmartTV) i use `scroll-into-view` apps development for.

**Pull request closed without merging**
