### PR TITLE
settings.validScrollable

### PR DESCRIPTION
**Pull request by vbarbarosh**
This is necessary for Firefox when using custom scrollbars. In this situation there is no other way to know that an element is used scrollbars.

This is an example of a component:

    <div class="custom-scrollbars">
        <div>...</div>
        <div class="scrollbar-track-x">...</div>
        <div class="scrollbar-track-y">...</div>
    </div>

    .custom-scrollbars > :first-child
        [...]
        overflow: scroll
        overflow: -moz-scrollbars-none // getComputedStyle(elem).overflow == 'hidden'
       -ms-overflow-style: none
       -webkit-overflow-scrolling: touch
       &::-webkit-scrollbar
           display: none

### CODE REVIEW

**Comment by KoryNunn** [comment]
Hi, this is an interesting feature.

I'm not sold on the naming, I think it should be `isScrollable` like the internal function.

Also, I'd like a test for this functionality.

**Comment by vbarbarosh** [comment]
I made a test.

Concerning `validScrollable` - I intentionally name it that way. I just want to _extend_ `isScrollable` a bit instead of overriding it compeletely. I don't want to include the following into my custom function:

    return (
        element === window ||
        (
            element.scrollHeight !== element.clientHeight ||
            element.scrollWidth !== element.clientWidth
        ) &&
        getComputedStyle(element).overflow !== 'hidden'
    );

If you want name `isScrollable` then it might work this way:

    var isScrollable = settings.isScrollable || defaultIsScrollalbe;

    while(parent){
        if(validTarget(parent, parents)){
            tmp = isScrollalbe(parent)); // *undefined* means _check for yourself_
            if (tmp === undefined) {
                tmp = defaultIsScrollalbe(parent);
            }
            if (tmp) {
                parents++;
                transitionScrollTo(target, parent, settings, done);
            }
        }

What do you think?

**Comment by KoryNunn** [comment]
I decided to allow the dev to overide isScrollable, to have more fine-grained control over what can be scrolled. The default isScrollable check function is passed as a second parameter, so it's easy to maintain that check if required.

**Comment by vbarbarosh** [comment]
Good solution. Thanks!

**Pull request merged**
